import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        error: "#ba1a1a",
        "on-primary": "#ffffff",
        "surface-container": "#eaeef2",
        "on-secondary-fixed-variant": "#7a3000",
        "on-secondary-container": "#572000",
        "on-primary-fixed": "#001b3e",
        "secondary-container": "#fe6b00",
        "on-surface": "#171c1f",
        "surface-variant": "#dfe3e7",
        "outline-variant": "#c4c6d0",
        "surface-bright": "#f6fafe",
        "on-tertiary-fixed-variant": "#38485d",
        "on-secondary-fixed": "#351000",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#aac7ff",
        surface: "#f6fafe",
        "primary-fixed": "#d6e3ff",
        "surface-container-low": "#f0f4f8",
        "tertiary-fixed": "#d3e4fe",
        "error-container": "#ffdad6",
        "surface-container-highest": "#dfe3e7",
        primary: "#001736",
        "tertiary-container": "#1d2d41",
        "inverse-primary": "#aac7ff",
        "on-surface-variant": "#43474f",
        "on-primary-fixed-variant": "#264779",
        "on-error-container": "#93000a",
        "on-background": "#171c1f",
        "inverse-surface": "#2c3134",
        "on-tertiary": "#ffffff",
        background: "#f6fafe",
        "tertiary-fixed-dim": "#b7c8e1",
        "on-tertiary-fixed": "#0b1c30",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#d6dade",
        "on-tertiary-container": "#8495ad",
        "secondary-fixed": "#ffdbcc",
        "on-primary-container": "#7594cb",
        "inverse-on-surface": "#edf1f5",
        "on-error": "#ffffff",
        outline: "#747780",
        secondary: "#a04100",
        "secondary-fixed-dim": "#ffb693",
        "surface-tint": "#3f5f92",
        "primary-container": "#002b5c",
        tertiary: "#07182b",
        "surface-container-high": "#e4e9ed",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "grid-size": "20px",
        "base-unit": "4px",
        "margin-desktop": "48px",
        "margin-mobile": "16px",
        gutter: "24px",
      },
      fontFamily: {
        "headline-lg": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"],
        "data-mono": ["JetBrains Mono"],
        "label-sm": ["JetBrains Mono"],
        "label-md": ["JetBrains Mono"],
        "headline-md": ["Hanken Grotesk"],
        "headline-lg-mobile": ["Hanken Grotesk"],
        "body-md": ["Hanken Grotesk"],
      },
      fontSize: {
        "headline-lg": [
          "40px",
          { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "data-mono": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "500" },
        ],
        "label-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg-mobile": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
      keyframes: {
        "fade-in": {
          from: { opacity: "0", transform: "translateY(8px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "fade-in": "fade-in 0.6s ease-out forwards",
      },
    },
  },
  plugins: [],
};
export default config;

